### PR TITLE
Add references to the fact jobhist requires userscripts

### PR DESCRIPTION
**Pull request by giordano**

### CODE REVIEW

**Comment by giordano** [comment]
Bump :slightly_smiling_face: A few weeks ago other users had the same troubles with `jobhist` not available.

**Comment by heatherkellyucl** [comment]
Aaaagh, there are a billionty lines of whitespace changes in this. The status page mention of jobhist comes from a past email to users so should be left alone, and the howto and job results pages are the only ones that should change.

**Comment by giordano** [comment]
> Aaaagh, there are a billionty lines of whitespace changes in this.

That's [a commit on its own](https://github.com/UCL-RITS/mkdocs-rc-docs/pull/73/commits/470fe6757a56224e75d06a3107372051c78471be), you can just look at [`f47fb3a` (#73)](https://github.com/UCL-RITS/mkdocs-rc-docs/pull/73/commits/f47fb3aab3cc4094e2a2aa15c372806bfb779e40), or [ignore whitespace changes](https://github.com/UCL-RITS/mkdocs-rc-docs/pull/73/files?w=1).  I can take the commit out into a separate PR, if you prefer.

> The status page mention of jobhist comes from a past email to users so should be left alone, and the howto and job results pages are the only ones that should change.

Ok, done!

**Review by heatherkellyucl — DISMISSED** [review]

**Comment by heatherkellyucl** [comment]
Yeah, please only include the content changes and leave the whitespace alone.

**Review by heatherkellyucl — APPROVED** [review]

**Pull request merged**
