### PR TITLE
Terms and Conditions Update

### PR DESCRIPTION
**Pull request by ikirker**
Updating the Terms and Conditions, as per [AHS-178](https://ucldata.atlassian.net/browse/AHS-178) and [AHS-114](https://ucldata.atlassian.net/browse/AHS-114).

[AHS-178]: https://ucldata.atlassian.net/browse/AHS-178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AHS-114]: https://ucldata.atlassian.net/browse/AHS-114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by heatherkellyucl** [comment]
The policies do apply to the ARC Cluster Filesystem, not to the other two.

**Comment by ikirker** [comment]
@heatherkellyucl That new page is kind of a mash of:

 - reference information on directories specific to our systems
 - reference information on directories *not* specific to our systems
 - policy information on our storage
 - conceptual information on filesystems
 - process information on our filesystems
 - attempts at guidance on filesystem use
 - attempts at guidance on longer-term data storage
 - information on user-to-user data transfer

Which, to me, reads more like "here's everything we can think of" or something more appropriate to a training session, rather than documentation?

Maybe there's a better way to divide it up and label the divisions to help people find what they're looking for, rather than relying on them reading the whole mostly-undifferentiated thing.

**Comment by heatherkellyucl** [comment]
I think the parallel filesystems concepts could go in Background alongside Cluster Computing, and then possibly the guidance on usage as well after that.

Then the On-cluster storage and filesystem retirement together in another page in there.

Leaving the Data Management page for how you do things.

**Comment by heatherkellyucl** [comment]
The content of the current how to on file transfers should move into Data Management too.

**Comment by heatherkellyucl** [comment]
Not sure if the tips on parallel filesystem use and filesystem retirement are in the right place, but they are somewhere.

**Pull request merged**
