### PR TITLE
Updating additional resources page with link to Myriad node purchases.

### PR DESCRIPTION
**Pull request by tcouch**

### CODE REVIEW

**Comment by tcouch** [comment]
This pull request now includes data science platform information.

**Review by heatherkellyucl — APPROVED** [review]

**Comment by ikirker** [comment]
Proposing that we revert this. We don't run or support this service, and IMO it's not appropriate to include documentation for it here.

It's also not really appropriate to jam the creation of a a large new section onto a PR labelled as a minor update to existing documentation.

**Comment by ikirker** [comment]
Oh gods, people doing careless merging has stuck together 11 different commits on several different topics into this one PR.

This is a mess.

**Comment by tcouch** [comment]
Sorry, I'm not exactly sure how I did that. In my haste to get it published, my pull request seems to have crash landed on top of an old one. I agree with reverting.

**Pull request merged**
